{% set version = '0.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pubmedr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pubmedR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pubmedR/pubmedR_{{ version }}.tar.gz
  sha256: 8d751e5e88480710a3f2687edb9cfdb66646e3c8a0fffcdfded92b1c49ca6b94

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-xml
    - r-rentrez
  run:
    - r-base
    - r-xml
    - r-rentrez

test:
  commands:
    - $R -e "library('pubmedR')"           # [not win]
    - "\"%R%\" -e \"library('pubmedR')\""  # [win]

about:
  home: https://github.com/massimoaria/pubmedR
  license: GPL-3.0-only
  summary: A set of tools to extract bibliographic content from 'PubMed' database using 'NCBI'
    REST API <https://www.ncbi.nlm.nih.gov/home/develop/api/>.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: pubmedR
# Title: Gathering Metadata About Publications, Grants, Clinical Trials from 'PubMed' Database
# Version: 0.0.3
# Authors@R: person(given = "Massimo", family = "Aria", role = c("aut", "cre"), email = "massimo.aria@gmail.com", comment = c(ORCID = "0000-0002-8517-9411"))
# Description: A set of tools to extract bibliographic content from 'PubMed' database using 'NCBI' REST API <https://www.ncbi.nlm.nih.gov/home/develop/api/>.
# License: GPL-3
# URL: https://github.com/massimoaria/pubmedR
# BugReports: https://github.com/massimoaria/pubmedR/issues
# Encoding: UTF-8
# LazyData: true
# Imports: rentrez, XML
# Suggests: bibliometrix, knitr, rmarkdown
# RoxygenNote: 7.1.0
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2020-07-09 10:40:28 UTC; massimoaria
# Author: Massimo Aria [aut, cre] (<https://orcid.org/0000-0002-8517-9411>)
# Maintainer: Massimo Aria <massimo.aria@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-07-09 11:00:02 UTC
